SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([ID], [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES (1, N'Bó hoa Hương Dương', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 1, NULL, 0)
SET IDENTITY_INSERT [dbo].[Product] OFF
/*Bó hoa*/
SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 1', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 2, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 2', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 3, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 3', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 4, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 4', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 5, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 5', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 6, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 6', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 7, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 7', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 8, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 8', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 9, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 9', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 10, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 10', N'BH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 11, NULL, 0)
SET IDENTITY_INSERT [dbo].[Product] OFF
/*Chậu hoa*/
SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 1', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 2, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 2', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 3, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 3', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 4, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 4', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 5, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 5', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 6, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 6', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 7, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 7', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 8, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 8', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 9, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 9', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 10, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 10', N'CH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 11, NULL, 0)
SET IDENTITY_INSERT [dbo].[Product] OFF
/*Lẳng hoa*/
SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 1', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 2, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 2', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 3, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 3', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 4, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 4', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 5, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 5', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 6, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 6', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 7, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 7', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 8, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 8', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 9, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 9', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 10, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 10', N'LH', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 11, NULL, 0)
SET IDENTITY_INSERT [dbo].[Product] OFF
SET IDENTITY_INSERT [dbo].[Product] ON
/*SP*/
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 1', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 2, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 2', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 3, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 3', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 4, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 4', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 5, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 5', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 6, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 6', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 7, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 7', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 8, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 8', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 9, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 9', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 10, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 10', N'SP', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 11, NULL, 0)
/*Trang chủ*/
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 1', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 2, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 2', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 3, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 3', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 4, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 4', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 5, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 5', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 6, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 6', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 7, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 7', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 8, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 8', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 9, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 9', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 10, NULL, 0)
INSERT INTO [dbo].[Product] ( [Name], [Code], [MetaTitle], [Description], [Avatar], [MoreImages], [Price], [PromotionPrice], [IncludeVAT], [Quantily], [CategoryID], [Detail], [Warranty], [CreatedDate], [CreatedBy], [ModifiedDate], [Mod], [MeteKeywords], [MetaDesciptions], [Status], [TopHot], [ViewCount]) VALUES ( N'Bó hoa Hương Dương 10', N'TC', N'không có gì', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'2019-12-08 08:39:33', NULL, NULL, NULL, NULL, NULL, 11, NULL, 0)


SET IDENTITY_INSERT [dbo].[Product] OFF


